<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

## *Data Science Unit 4 Sprint 2*

# Sprint Challenge - Neural Network Foundations

Table of Problems

1. [Defining Neural Networks](#Q1)
2. [Chocolate Gummy Bears](#Q2)
    - Perceptron
    - Multilayer Perceptron
4. [Keras MMP](#Q3)

<a id="Q1"></a>
## 1. Define the following terms:

- **Neuron:**
    A Neuron is a single node within a Neural Network.
- **Input Layer:**
    The input layer is the highest level layer, where we input our data into the Neural Network
- **Hidden Layer:**
    Hidden layers are generally called that because we really don't have much access to them. 
    They're the layers where a lot of the neural network magic happens, crunching ming numbing
    amounts of numbers in a fraction of the time our minds could work through them.
- **Output Layer:**
    The output layer is where we see what our Neural Network comes up with. In some cases
    this means that we see a prediction of something. In others, a new thing, based on a lot
    of old things.
- **Activation:**
    Activation in a neural network is like a neuron firing! It's a big part of the math that 
    allows a feed forward Neural Network to make sense of the relationships in data.
- **Backpropagation:**
    Backpropagation is a method of sending all the information learned, backwards in the network.
    The process updates our original weights, allowing the model to fit even more effectively to the
    data.


## 2. Chocolate Gummy Bears <a id="Q2"></a>

Right now, you're probably thinking, "yuck, who the hell would eat that?". Great question. Your candy company wants to know too. And you thought I was kidding about the [Chocolate Gummy Bears](https://nuts.com/chocolatessweets/gummies/gummy-bears/milk-gummy-bears.html?utm_source=google&utm_medium=cpc&adpos=1o1&gclid=Cj0KCQjwrfvsBRD7ARIsAKuDvMOZrysDku3jGuWaDqf9TrV3x5JLXt1eqnVhN0KM6fMcbA1nod3h8AwaAvWwEALw_wcB). 

Let's assume that a candy company has gone out and collected information on the types of Halloween candy kids ate. Our candy company wants to predict the eating behavior of witches, warlocks, and ghosts -- aka costumed kids. They shared a sample dataset with us. Each row represents a piece of candy that a costumed child was presented with during "trick" or "treat". We know if the candy was `chocolate` (or not chocolate) or `gummy` (or not gummy). Your goal is to predict if the costumed kid `ate` the piece of candy. 

If both chocolate and gummy equal one, you've got a chocolate gummy bear on your hands!?!?!
![Chocolate Gummy Bear](https://ed910ae2d60f0d25bcb8-80550f96b5feb12604f4f720bfefb46d.ssl.cf1.rackcdn.com/3fb630c04435b7b5-2leZuM7_-zoom.jpg)

In [1]:
import pandas as pd
candy = pd.read_csv('chocolate_gummy_bears.csv')

In [2]:
candy.head()

chocolate  gummy  ate
0          0      1    1
1          1      0    1
2          0      1    1
3          0      0    0
4          1      1    0

### Perceptron

To make predictions on the `candy` dataframe. Build and train a Perceptron using numpy. Your target column is `ate` and your features: `chocolate` and `gummy`. Do not do any feature engineering. :P

Once you've trained your model, report your accuracy. You will not be able to achieve more than ~50% with the simple perceptron. Explain why you could not achieve a higher accuracy with the *simple perceptron* architecture, because it's possible to achieve ~95% accuracy on this dataset. Provide your answer in markdown (and *optional* data anlysis code) after your perceptron implementation. 

In [11]:
# Start your candy perceptron here

X = candy[['chocolate', 'gummy']].values
y = candy['ate'].values

In [7]:
#The import slave...I mean cell
import numpy as np
#Set random seed for reproducibility
np.random.seed(42)

In [3]:
#Defining a sigmoid function for my perceptron
def sigmoid(x):
    return 1/ (1 + np.exp(-x))

In [16]:
#Establish a set of random weights
weights = np.random.random((2,10000))
weights

array([[0.05808361, 0.86617615, 0.60111501, ..., 0.60726667, 0.47662416,
        0.86570099],
       [0.03210958, 0.64386793, 0.76294888, ..., 0.66328064, 0.48208934,
        0.73857104]])

In [23]:
#Impliment basic perceptron calculate weighted sum
weighted_sum = np.dot(X, weights)
#calculate acticvated output of perceptron(prediction)
activated_output = sigmoid(weighted_sum)
print(weighted_sum)
print(activated_output)

[[0.95071431]
 [0.37454012]
 [0.95071431]
 ...
 [0.95071431]
 [0.95071431]
 [0.37454012]]
[[0.72125881]
 [0.59255557]
 [0.72125881]
 ...
 [0.72125881]
 [0.72125881]
 [0.59255557]]


In [7]:
from sklearn.metrics import mean_squared_error
#Calculate error
print(mean_squared_error(y, activated_output))

NameError: name 'activated_output' is not defined

In [4]:
#Define sigmoid derivative to adjust weights with each epoch
def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1 - sx)

In [20]:
for iteration in range(100):
    #Calculate input times weights
    weighted_sum = np.dot(X, weights)
    #Run through activation function
    activated_output = sigmoid(weighted_sum)
    #Calculate the error
    error = y - activated_output
    #Calculate adjustments
    adjustments = error * sigmoid_derivative(activated_output)
    #Adjust weights
    weights += np.dot(X.T, adjustments)
    print("Epoch Complete")
    
print(f"Weights after training: {weights}")
print(f"Output after training: {activated_output}")

Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Complete
Epoch Comp

### Multilayer Perceptron <a id="Q3"></a>

Using the sample candy dataset, implement a Neural Network Multilayer Perceptron class that uses backpropagation to update the network's weights. Your Multilayer Perceptron should be implemented in Numpy. 
Your network must have one hidden layer.

Once you've trained your model, report your accuracy. Explain why your MLP's performance is considerably better than your simple perceptron's on the candy dataset. 

In [13]:
class NeuralNetwork:
    def __init__(self):

        #Establish neural network architecture
        #Specify number of nodes in each layer
        
        self.inputs = 2
        self.hiddenNodes = 3
        self.outputNodes = 10000

        #Randomly initialize weights input layer -> hidden layer
        self.weights1 = np.random.rand(self.inputs, self.hiddenNodes)
       
        #Random intitialize weights hidden layer -> output layer
        self.weights2 = np.random.rand(self.hiddenNodes, self.outputNodes)
        
    def sigmoid(self, x):
        #Adding sigmoid function to actual class
        return 1/ (1 + np.exp(-x))
    
    def sigmoidPrime(self,z):
        #Gradient of sigmoid
        return np.exp(-z)/((1+np.exp(-z))**2)
        
    def feed_forward(self, X):
        """
        impliment above logic to create the feed forward portion
        """
       
        #Combining inputs and weights in a weighted sum
        self.hidden_sum = np.dot(X, self.weights1)
        
        #Apply activation function to the hidden layer weight sums. 
        #Activated values
        self.activated_hidden = self.sigmoid(self.hidden_sum)
        
        #Weighted sum hidden layer and the output
        self.output_sum = np.dot(self.activated_hidden, self.weights2)
        
        #Apply activation function to the output weighted sums
        self.activated_output = self.sigmoid(self.output_sum)
        
        return self.activated_output
    
    def backward(self, X,y,o):
        """
        Send the new information back through the network
        """
        
        #Calculate the error
        self.o_error = y - o
        
        #Apply sigmoid derivative to the error. 
        #Which direction do we want go?
        self.o_delta = self.o_error * self.sigmoidPrime(o)
        
        #How much our hidden layer weights contributed to output error.
        self.z2_error = self.o_delta.dot(self.weights2.T)
        
        #Apply sigmoid derivative to the error. 
        self.z2_delta = self.z2_error * self.sigmoidPrime(self.activated_hidden)
        
        #Applying adjustments to the weights.
        self.weights1 += X.T.dot(self.z2_delta)
        
        #Applying adjustments to the weights.
        self.weights2 += self.activated_hidden.T.dot(self.o_delta)
        
    def train(self, X, y):
        #Simple training function from class.
        o = self.feed_forward(X)
        self.backward(X,y,o)

In [14]:
nn = NeuralNetwork()

In [32]:
"""Commented out testing cell, but left it in place to be seen."""

# weights1 = np.random.rand(2,3)
# weights2 = np.random.rand(3,10000)
# def feed_forward(X):
#     """
#     impliment above logic to create the feed forward portion
#     """
       
#     #Combining inputs and weights in a weighted sum
#     hidden_sum = np.dot(X, weights1)
        
#     #Apply activation function to the hidden layer weight sums. 
#     #Activated values
#     activated_hidden = sigmoid(hidden_sum)
        
#     #Weighted sum hidden layer and the output
#     output_sum = np.dot(activated_hidden, weights2)
        
#     #Apply activation function to the output weighted sums
#     activated_output = sigmoid(output_sum)
        
#     return activated_output, activated_hidden

In [26]:
o_a_h = feed_forward(X)
o = o_a_h[0]

In [34]:
"""More Testing"""

# def sigmoidPrime(z):
#         #Gradient of sigmoid
#         return np.exp(-z)/((1+np.exp(-z))**2)

# weights1 = np.random.rand(2,3)
# weights2 = np.random.rand(3,10000)    

# def backward(X,y,o, weights1, weights2):
#     activated_hidden = o_a_h[1]
    
#     #Calculate the error
#     o_error = y - o
    
#     #Apply sigmoid derivative to the error. 
#     #Which direction do we want go?
#     o_delta = o_error * sigmoidPrime(o)

#     #How much our hidden layer weights contributed to output error.
#     z2_error = o_delta.dot(weights2.T)

#     #Apply sigmoid derivative to the error. 
#     z2_delta = z2_error * sigmoidPrime(activated_hidden)

#     #Applying adjustments to the weights.
#     weights1 += X.T.dot(z2_delta)

#     #Applying adjustments to the weights.
#     weights2 += activated_hidden.T.dot(o_delta)

In [35]:
"""Figured it out!"""
#I can't figure this error out and it makes absolutely zero sense to me.
# backward(X,y,o,weights1,weights2)

In [36]:
y2 = y.reshape(-1)
y2.shape

(10000,)

In [37]:
o2 = o[0].reshape(-1)
o2.shape

(10000,)

In [15]:
nn.train(X,y)

In [ ]:
#Borrowed training loop from lecture notebook
# Number of Epochs / Iterations is small for times sake
for i in range(50):
    if (i+1 in [1,2,3,4,5]) or ((i+1) % 1000 ==0):
        print('+' + '---' * 3 + f'EPOCH {i+1}' + '---'*3 + '+')
        print('Input: \n', X)
        print('Actual Output: \n', y)
        print('Predicted Output: \n', str(nn.feed_forward(X)))
        print("Loss: \n", str(np.mean(np.square(y - nn.feed_forward(X)))))
    nn.train(X,y)
    
#Model overfit to data very quickly and I'm honestly concerned this isn't the right setup.

+---------EPOCH 1---------+
Input: 
 [[0 1]
 [1 0]
 [0 1]
 ...
 [0 1]
 [0 1]
 [1 0]]
Actual Output: 
 [1 1 1 ... 1 1 1]
Predicted Output: 
 [[0.5 0.5 0.5 ... 0.5 0.5 0.5]
 [0.5 0.5 0.5 ... 0.5 0.5 0.5]
 [0.5 0.5 0.5 ... 0.5 0.5 0.5]
 ...
 [0.5 0.5 0.5 ... 0.5 0.5 0.5]
 [0.5 0.5 0.5 ... 0.5 0.5 0.5]
 [0.5 0.5 0.5 ... 0.5 0.5 0.5]]
Loss: 
 0.18705
+---------EPOCH 2---------+
Input: 
 [[0 1]
 [1 0]
 [0 1]
 ...
 [0 1]
 [0 1]
 [1 0]]
Actual Output: 
 [1 1 1 ... 1 1 1]
Predicted Output: 
 [[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
Loss: 
 0.0
+---------EPOCH 3---------+
Input: 
 [[0 1]
 [1 0]
 [0 1]
 ...
 [0 1]
 [0 1]
 [1 0]]
Actual Output: 
 [1 1 1 ... 1 1 1]
Predicted Output: 
 [[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
Loss: 
 0.0
+---------EPOCH 4---------+
Input: 


P.S. Don't try candy gummy bears. They're disgusting. 

## 3. Keras MMP <a id="Q3"></a>

Implement a Multilayer Perceptron architecture of your choosing using the Keras library. Train your model and report its baseline accuracy. Then hyperparameter tune at least two parameters and report your model's accuracy.
Use the Heart Disease Dataset (binary classification)
Use an appropriate loss function for a binary classification task
Use an appropriate activation function on the final layer of your network.
Train your model using verbose output for ease of grading.
Use GridSearchCV or RandomSearchCV to hyperparameter tune your model. (for at least two hyperparameters)
When hyperparameter tuning, show you work by adding code cells for each new experiment.
Report the accuracy for each combination of hyperparameters as you test them so that we can easily see which resulted in the highest accuracy.
You must hyperparameter tune at least 3 parameters in order to get a 3 on this section.

In [2]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

df = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/heart.csv')
df = df.sample(frac=1)
print(df.shape)
df.head()

(303, 14)


age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
160   56    1   1       120   240    0        1      169      0      0.0   
196   46    1   2       150   231    0        1      147      0      3.6   
7     44    1   1       120   263    0        1      173      0      0.0   
226   62    1   1       120   281    0        0      103      0      1.4   
273   58    1   0       100   234    0        1      156      0      0.1   

     slope  ca  thal  target  
160      0   0     2       1  
196      1   0     2       0  
7        2   0     3       1  
226      1   1     3       0  
273      2   1     3       0

In [3]:
#Import Keras parts
from sklearn.model_selection import train_test_split
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier

In [10]:
#Establish build function for KerasClassifier
def create_model():
    model = Sequential()
    model.add(Dense(10, input_dim=13, activation="relu"))
    model.add(Dense(16, activation="sigmoid"))
    model.add(Dense(1, activation="sigmoid"))
    model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])
    return model

In [11]:
kc = KerasClassifier(build_fn=create_model, verbose=1)

In [12]:
X = df.drop("target", axis=1)
y = df["target"]

In [7]:
#Establish X/y test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)
#Establish X/y train and validation sets
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.33)

In [8]:
#Initial baseline fit
kc.fit(X_train, y_train)

Train on 136 samples
136/136 [==============================] - 0s 543us/sample - loss: 0.7002 - accuracy: 0.5368


In [13]:
#adding epochs
kc.fit(X_train, y_train, epochs=50)

Train on 136 samples
Epoch 1/50
136/136 [==============================] - 0s 792us/sample - loss: 0.9041 - accuracy: 0.4559
Epoch 2/50
136/136 [==============================] - 0s 73us/sample - loss: 0.8673 - accuracy: 0.4559
Epoch 3/50
136/136 [==============================] - 0s 51us/sample - loss: 0.8301 - accuracy: 0.4632
Epoch 4/50
136/136 [==============================] - 0s 59us/sample - loss: 0.7890 - accuracy: 0.4632
Epoch 5/50
136/136 [==============================] - 0s 59us/sample - loss: 0.7662 - accuracy: 0.4632
Epoch 6/50
136/136 [==============================] - 0s 51us/sample - loss: 0.7484 - accuracy: 0.4632
Epoch 7/50
136/136 [==============================] - 0s 59us/sample - loss: 0.7399 - accuracy: 0.4632
Epoch 8/50
136/136 [==============================] - 0s 51us/sample - loss: 0.7341 - accuracy: 0.4632
Epoch 9/50
136/136 [==============================] - 0s 66us/sample - loss: 0.7281 - accuracy: 0.4632
Epoch 10/50
136/136 [==============================

In [14]:
from sklearn.model_selection import GridSearchCV

param_grid = {'batch_size':[1,5,10],
              'epochs':[15,30,45]}

grid = GridSearchCV(estimator=kc, param_grid=param_grid)

In [15]:
results = grid.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


Train on 90 samples
Epoch 1/15
90/90 [==============================] - 0s 2ms/sample - loss: 0.7594 - accuracy: 0.5778
Epoch 2/15
90/90 [==============================] - 0s 909us/sample - loss: 0.7272 - accuracy: 0.5778
Epoch 3/15
90/90 [==============================] - 0s 975us/sample - loss: 0.7056 - accuracy: 0.5778
Epoch 4/15
90/90 [==============================] - 0s 920us/sample - loss: 0.6984 - accuracy: 0.5778
Epoch 5/15
90/90 [==============================] - 0s 842us/sample - loss: 0.6947 - accuracy: 0.5778
Epoch 6/15
90/90 [==============================] - 0s 931us/sample - loss: 0.6902 - accuracy: 0.5778
Epoch 7/15
90/90 [==============================] - 0s 875us/sample - loss: 0.6879 - accuracy: 0.5778
Epoch 8/15
90/90 [==============================] - 0s 931us/sample - loss: 0.6852 - accuracy: 0.5778
Epoch 9/15
90/90 [==============================] - 0s 909us/sample - loss: 0.6841 - accuracy: 0.5778
Epoch 10/15
90/90 [==============================] - 0s 920us/sa

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


Train on 136 samples
Epoch 1/45
136/136 [==============================] - 0s 1ms/sample - loss: 0.6926 - accuracy: 0.5441
Epoch 2/45
136/136 [==============================] - 0s 777us/sample - loss: 0.6842 - accuracy: 0.5441
Epoch 3/45
136/136 [==============================] - 0s 777us/sample - loss: 0.6866 - accuracy: 0.5441
Epoch 4/45
136/136 [==============================] - 0s 939us/sample - loss: 0.6919 - accuracy: 0.5441
Epoch 5/45
136/136 [==============================] - 0s 924us/sample - loss: 0.6925 - accuracy: 0.5441
Epoch 6/45
136/136 [==============================] - 0s 917us/sample - loss: 0.6825 - accuracy: 0.5441
Epoch 7/45
136/136 [==============================] - 0s 770us/sample - loss: 0.6867 - accuracy: 0.5441
Epoch 8/45
136/136 [==============================] - 0s 792us/sample - loss: 0.6797 - accuracy: 0.5441
Epoch 9/45
136/136 [==============================] - 0s 755us/sample - loss: 0.6843 - accuracy: 0.5441
Epoch 10/45
136/136 [========================